services:
    springboot:
      image: springbootapp
      container_name: mi-springboot
      ports:
        - "8088:8080"
      environment:
        DBNAME: ejemplo
        DBUSER: ejemplo
        DBPASS: test1234
        DBHOST: un-mariadb
      depends_on:
        - mariadb-development
        - rabbitmq
      restart: unless-stopped        
    mariadb-development:
      image: mariadb
      container_name: un-mariadb
      environment:
        MARIADB_ROOT_PASSWORD: test1234
        MARIADB_DATABASE: ejemplo
        MARIADB_USER: ejemplo
        MARIADB_PASSWORD: test1234
      #ports:
      #  - "3306:3306"
      volumes:
        - "../mariadb-volume:/var/lib/mysql"
      restart: unless-stopped  
    rabbitmq:
      image: rabbitmq:3
      container_name: un-rabbitmq
      restart: unless-stopped  