services:
    springboot:
      image: springbootapp
      container_name: mi-springboot
      ports:
        - "8088:8080"
      environment:
        MYSQL_DBNAME: ejemplo
        MYSQL_DBUSER: ejemplo
        MYSQL_DBPASS: test1234
        MYSQL_DBHOST: un-mysql
      depends_on:
        - mysql-development
        - rabbitmq
      restart: unless-stopped        
    mysql-development:
      image: mysql
      container_name: un-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: test1234
        MYSQL_DATABASE: ejemplo
        MYSQL_USER: ejemplo
        MYSQL_PASSWORD: test1234
      #ports:
      #  - "3306:3306"
      working_dir: /var/lib/mysql
      volumes:
        - "../mysql-volume:/var/lib/mysql"
      restart: unless-stopped  
    rabbitmq:
      image: rabbitmq:3
      container_name: un-rabbitmq
      restart: unless-stopped  