FROM eclipse-temurin:22-jdk-jammy AS builder

WORKDIR /app

ADD demo/ .

RUN ./mvnw clean install


FROM eclipse-temurin:22-jdk-jammy

WORKDIR /app

EXPOSE 8080

COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT.jar /app/app.jar

CMD ["java", "-jar", "/app/app.jar"]